name: Node.js Package

on:
  push:
    branches: 
      -main
      
jobs:
  publish-gpr
    runs-on:windows-latest
      steps:
        -uses: actions/checkout@v2
        -uses: actions/setupnode@v1
        with:
        node version:12
        registory-url: https://npm.pkg.github.com/
        scope:'@harryvd16'
      -run: npm install
      -run: npm publish
      env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
